version: "3"

services:
  front:
    image: st116vm101.rtb-lab.pl:443/pds-front
    ports:
      - "8080:8080"
    deploy:
      replicas: 4
      restart_policy:
        condition: any

  # Mongo
  # Mongo-config
  mongo-config:
    image: mongo
    command: mongod --port 27017 --configsvr --replSet rs-config --bind_ip_all
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    deploy:
      replicas: 3
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  mongo-config-init:
    image: st116vm101.rtb-lab.pl:443/pds-scripts-mongo
    entrypoint: sh /config-init.sh
    deploy:
      restart_policy:
        condition: on-failure

  # Mongo-shard-a
  mongo-shard-a:
    image: mongo
    command: mongod --port 27017 --shardsvr --replSet rs-shard-a --bind_ip_all
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    deploy:
      replicas: 3
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  mongo-shard-a-init:
    image: st116vm101.rtb-lab.pl:443/pds-scripts-mongo
    entrypoint: sh /shard-a-init.sh
    deploy:
      restart_policy:
        condition: on-failure

  # Mongo-shard-b
  mongo-shard-b:
    image: mongo
    command: mongod --port 27017 --shardsvr --replSet rs-shard-b --bind_ip_all
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    deploy:
      replicas: 3
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  mongo-shard-b-init:
    image: st116vm101.rtb-lab.pl:443/pds-scripts-mongo
    entrypoint: sh /shard-b-init.sh
    deploy:
      restart_policy:
        condition: on-failure

  # Mongo-shard-c
  mongo-shard-c:
    image: mongo
    command: mongod --port 27017 --shardsvr --replSet rs-shard-c --bind_ip_all
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    deploy:
      replicas: 3
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  mongo-shard-c-init:
    image: st116vm101.rtb-lab.pl:443/pds-scripts-mongo
    entrypoint: sh /shard-c-init.sh
    deploy:
      restart_policy:
        condition: on-failure

  # Mongo-router
  mongo-router:
    image: mongo
    command: mongos --configdb rs-config/pds_mongo-config.1:27017,pds_mongo-config.2:27017,pds_mongo-config.3:27017 --bind_ip_all
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    deploy:
      replicas: 3
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  mongo-router-init:
    image: st116vm101.rtb-lab.pl:443/pds-scripts-mongo
    entrypoint: sh /router-init.sh
    deploy:
      restart_policy:
        condition: on-failure
