name:                front
version:             0.1.0.0
github:              "githubuser/front"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/front#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- wai
- wai-extra
- warp
- time
- text
- raw-strings-qq
- http-types
- bytestring
- mtl
- containers
- extra
- data-has
- mongoDB
- AesonBson

default-extensions:
- QuasiQuotes
- ScopedTypeVariables
- DataKinds
- TypeOperators
- DerivingStrategies
- GeneralizedNewtypeDeriving
- RecordWildCards
- NamedFieldPuns
- FlexibleContexts
- TupleSections
- LambdaCase

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  front-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - front
